---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

Unzip the data
```r
Sys.setlocale("LC_TIME", "en_US.UTF-8")
    unzip('activity.zip')
```

now load the CSV
```{r}
    data <- read.csv('activity.csv')
    summary(data)
    data$date <- as.Date(data$date)

```

## What is mean total number of steps taken per day?
```{r}
aggregated <- aggregate(steps ~ date, data, sum)
mean(aggregated$steps)
median(aggregated$steps)
library(ggplot2)
qplot(date, steps, data=aggregated, geom="bar", stat="identity");
```

## What is the average daily activity pattern?
```{r}
aggregated <- aggregate(steps ~ interval, data, mean)
qplot(interval, steps, data=aggregated, geom="line");
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
```{r}
    data$day <- weekdays(data$date)
    data$weekday <- data$day != 'Saturday' & data$day != 'Sunday'
    aggregated <- aggregate(steps ~ interval + weekday, data, mean)
    qplot(interval, steps, data=aggregated, geom="line", color=weekday);

```
